<?php $labelsData = $this->getLabelsData(); ?>
<?php $rem = $this->getLabelsRem(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt" lang="pt">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Endere&ccedil;ador</title>
    <style type="text/css">
        @media print {
            @page {
                margin: 0;
                width: 100%;
                height: 100%;
            }
        }

        body {
            width: 100%;
            height: 100%;
            margin: 0;
        }

        .divPageRow {
            display: inline-block;
            width: 100%;
            margin: 2.5mm 2.5mm 0 2.5mm;
        }

        .divPage {
            width: 210mm;
            height: 297mm;
        }

        .divLabel {
            margin: 2.5mm;
            /*border-width: thin;
                border-color: black;
                border-style: solid;*/
            float: left;
            height: 144mm;
            width: 100mm;
        }

        .labelContent {
            max-width: 100%;
            max-height: 144mm;
            overflow: hidden;
        }

        .labelHeaderReserved {
            max-width: 100%;
            height: 42mm;
            margin: 0mm 0mm 5mm 0mm;
            border-style: dashed;
            border-width: 2px;
            border-color: black;
            display: inline-block;
            width: 99%;
        }

            .labelHeaderReserved div {
                text-align: center;
            }

        .labelHeaderImages {
            height: 8mm;
            display: inline-block;
            width: 100%;
        }

        .labelMiddleContent {
            height: 65mm;
            display: inline-block;
            width: 100%;
        }

        .labelColumn1 {
            height: 100%;
        }

            .labelColumn1 div {
                float: left;
                text-align: center;
                width: 100%;
            }

        .labelAddress {
            text-align: left !important;
            font-size: 4mm;
            margin-left: 5mm;
            font-weight: bold;
        }

        .labelAddressBarCode {
            text-align: center;
        }

        .labelOrderBarCode {
            width: 70% !important;
        }

        .labelOrderDetails {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 18px;
            width: 40mm;
            height: 20mm;
        }

        .labelSeparator {
            width: 100%;
            border: 0 none black;
            border-top: 2px solid black;
            margin: 0mm 0mm 1mm 0mm;
        }

        .labelFrom {
            font-family: Arial,Helvetica,sans-serif;
            font-size: 3mm;
        }

        .rotate {
            -moz-transform: rotate(-90.0deg) translate(20mm,70mm); /* FF3.5+ */
            -o-transform: rotate(-90.0deg) translate(20mm,70mm); /* Opera 10.5 */
            -webkit-transform: rotate(-90.0deg) translate(20mm,70mm); /* Saf3.1+, Chrome */
            filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=0.083); /* IE6,IE7 */
            -ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=0.083)"; /* IE8 */
        }
    </style>
    <script type="text/javascript">
        function edit(field) {
            field.onclick = null;
            var text = field.innerHTML;
            var input = '<input type="text" value="' + text + '" />';
            field.innerHTML = input;
            field.firstChild.focus();
            field.firstChild.select();
            field.firstChild.onblur = function () {
                if (field.firstChild.value == "") {
                    field.firstChild.value = "&nbsp;";
                }
                field.innerHTML = field.firstChild.value;
                field.onclick = function () { edit(this); };
            }
        }
    </script>
</head>
<body>
    <div>
        <?php $e = 1; ?>
        <?php for($p = 1; $p <= $this->getPagesCount(); $p++): ?>
        <div class="divPage">
            <?php for($i = 1; $i <= min(2, $this->getLabelsCount() - 4 * ($p -1) ); $i++) : ?>
            <div class="divPageRow">
                <?php for($j = 1; $j <= min(2, $this->getLabelsCount() - 4 * ($p - 1) - 2 * ($i - 1) ); $j++) : ?>
                <div class="divLabel">
                    <div class="labelContent">
                        <div class="labelHeaderReserved">
                            <div>USO EXCLUSIVO DOS CORREIOS</div>
                            <div class="labelOrderBarCode">
                                <br
                                <?php foreach ($labelsData[$e-1]['orderbarcode'] as $code): ?>
                                /><img src="<?php echo $this->getSkinUrl('images/etiquetaendereco/') . $code['type'] . '.gif' ?>"
                                        width="<?php echo $code['value'] ?>" height="90" alt=""
                                <?php endforeach ?>
                                /><br />
                            </div>
                            <div class="labelOrderDetails rotate">
                                <strong>#<?php echo $labelsData[$e-1]['order'] ?></strong></br>
                                <?php if($labelsData[$e-1]['shipping']): ?>
                                <strong><?php echo $labelsData[$e-1]['shipping'] ?></strong>
                                <?php endif; ?>
                                <?php if($labelsData[$e-1]['tracking']): ?>
                                <strong><?php echo $labelsData[$e-1]['tracking'] ?></strong>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="labelHeaderImages">
                            <div style="float:left">
                                <img src="<?php echo $this->getSkinUrl('images/etiquetaendereco/destinatario_peq.gif') ?>" border="0" alt="" />
                            </div>
                            <div style="float:right">
                                <img src="<?php echo $this->getSkinUrl('images/etiquetaendereco/logo_correios_peq.gif') ?>" border="0" alt="" />
                            </div>
                        </div>
                        <div class="labelMiddleContent">
                            <div class="labelColumn1">
                                <div class="labelAddress">
                                    <?php if ($labelsData[$e-1]['name1']): ?>
                                    <span onclick="edit(this)"><?php echo $labelsData[$e-1]['name1'] ?></span><br />
                                    <?php endif; ?>
                                    <?php if ($labelsData[$e-1]['name2']): ?>
                                    <span onclick="edit(this)"><?php echo $labelsData[$e-1]['name2'] ?></span><br />
                                    <?php endif; ?>
                                    <?php if ($labelsData[$e-1]['fone']): ?>
                                    <span onclick="edit(this)">Fone: <?php echo $labelsData[$e-1]['fone'] ?></span><br />
                                    <?php endif; ?>
                                    <span onclick="edit(this)"><?php echo $labelsData[$e-1]['street'] ?><?php echo $labelsData[$e-1]['num'] ? ', '.$labelsData[$e-1]['num']:'' ?></span><br />
                                    <?php if ($labelsData[$e-1]['compl']): ?>
                                    <span onclick="edit(this)"><?php echo $labelsData[$e-1]['compl'] ?></span><br />
                                    <?php endif; ?>
                                    <?php if ($labelsData[$e-1]['bairro']): ?>
                                    <span onclick="edit(this)"><?php echo $labelsData[$e-1]['bairro'] ?></span><br />
                                    <?php endif; ?>
                                    <span onclick="edit(this)"><?php echo $labelsData[$e-1]['city'] ?> / <?php echo $labelsData[$e-1]['uf'] ?></span><br />
                                    <?php echo $labelsData[$e-1]['zipcode'] ?>
                                </div>
                                <div class="labelAddressBarCode">
                                    <div>
                                        <br
                                        <?php foreach ($labelsData[$e-1]['zipbarcode'] as $code): ?>
                                        /><img src="<?php echo $this->getSkinUrl('images/etiquetaendereco/') . $code['type'] . '.gif' ?>" width="<?php echo $code['value'] ?>" height="90" alt=""
                                        <?php endforeach ?>
                                        /><br />
                                    </div>
                                    <div>
                                        <strong><?php echo $labelsData[$e-1]['zipcode'] ?></strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="labelSeparator" />
                        <div class="labelFrom">
                            <b>Remetente:</b><br />
                            <?php if ($rem['name1']):?>
                            <span onclick="edit(this)"><?php echo $rem['name1'] ?></span><br />
                            <?php endif; ?>
                            <?php if ($rem['name2']):?>
                            <span onclick="edit(this)"><?php echo $rem['name2'] ?></span><br />
                            <?php endif; ?>
                            <?php if ($rem['fone']):?>
                            <span onclick="edit(this)"><?php echo $rem['fone'] ?></span><br />
                            <?php endif; ?>
                            <span onclick="edit(this)"><?php echo $rem['address'] ?></span><br />
                            <?php if ($rem['compl']):?>
                            <span onclick="edit(this)"><?php echo $rem['compl']?></span><br />
                            <?php endif; ?>
                            <span onclick="edit(this)"><?php echo $rem['bairro']?></span><br />
                            <span onclick="edit(this)"><?php echo $rem['zipcode']?> - <?php echo $rem['city']?></span>
                        </div>
                    </div>
                </div>
                <?php $e++; ?>
                <?php endfor; ?>
            </div>
            <?php endfor; ?>
        </div>
        <?php if ($p < $this->getPagesCount()): ?>
        <div style="page-break-after: always;"></div>
        <div style="margin-top: 8px;"></div>
        <?php endif; ?>
        <?php endfor; ?>
    </div>
</body>
</html>
